import Head from 'next/head'
import Home from '../views/Home/Home'

export default function Index() {


  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

    </div>
  )
}
