import Head from 'next/head'
import { useState } from 'react';

export default function Home() {

  const [message, setMessage] = useState('');

  const handleSend = () => {
    e.preventDefault();
  }

  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action="" className='text-center mt-5' onSubmit={handleSend}>
        <div className="mb-6">
          <label className="block text-gray-700 text-sm font-bold mb-2" for="password">
            Password
          </label>
          <input
            id="password"
            type="text"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            className="shadow appearance-none border border-red-500 rounded py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
            placeholder="Write your message here"
          />
          <p className="text-red-500 text-xs italic">Please choose a password.</p>
        </div>

        <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" >
          Send
        </button>
      </form>

    </div>
  )
}
