import Head from 'next/head'
import { useEffect, useState } from 'react';
import useSocket from '../hooks/useSocket';

export default function Home() {

  // hooks
  const { socket } = useSocket();

  // states
  const [message, setMessage] = useState('');

  // socket emit
  useEffect(() => {
    if (!socket) return;
    socket.on('message-form-server', () => {
      console.log('message got');
    })

  }, [socket])

  // messge send fn
  const handleSend = (e) => {
    e.preventDefault();
    if (message) {
      socket.emit('send-message', { message });
    }
  }

  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <form className='mt-5' onSubmit={handleSend}>

          <div className="mb-3 xl:w-96">
            <label htmlFor="message" className="form-label inline-block mb-2 text-gray-700 !text-start">Mesage</label>
            <input
              type="text"
              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              id="message"
              placeholder="Write your message here"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
            />
          </div>

          <button type="submit" className="bg-blue-500 w-max hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Send</button>

        </form>
      </div>

    </div>
  )
}
